[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
fs_permissions = [{ access = "read", path = "./"}]
ffi = true
ast = true
build_info = true
evm_version = "cancun"
extra_output = ["storageLayout"]

[rpc_endpoints]
sonic_testnet = "${SONIC_BLAZE_TESTNET_RPC_URL}"
sonic_mainnet = "${SONIC_MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
